/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParcheCrearRouteImport } from './routes/parche.crear'
import { Route as ParcheCodeRouteImport } from './routes/parche.$code'
import { Route as ParcheCodeQuizRouteImport } from './routes/parche_.$code.quiz'
import { Route as ParcheCodeMatchRouteImport } from './routes/parche_.$code.match'

const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCrearRoute = ParcheCrearRouteImport.update({
  id: '/parche/crear',
  path: '/parche/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCodeRoute = ParcheCodeRouteImport.update({
  id: '/parche/$code',
  path: '/parche/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCodeQuizRoute = ParcheCodeQuizRouteImport.update({
  id: '/parche_/$code/quiz',
  path: '/parche/$code/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheCodeMatchRoute = ParcheCodeMatchRouteImport.update({
  id: '/parche_/$code/match',
  path: '/parche/$code/match',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/registro': typeof RegistroRoute
  '/telegram': typeof TelegramRoute
  '/parche/$code': typeof ParcheCodeRoute
  '/parche/crear': typeof ParcheCrearRoute
  '/parche/$code/match': typeof ParcheCodeMatchRoute
  '/parche/$code/quiz': typeof ParcheCodeQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/registro': typeof RegistroRoute
  '/telegram': typeof TelegramRoute
  '/parche/$code': typeof ParcheCodeRoute
  '/parche/crear': typeof ParcheCrearRoute
  '/parche/$code/match': typeof ParcheCodeMatchRoute
  '/parche/$code/quiz': typeof ParcheCodeQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/registro': typeof RegistroRoute
  '/telegram': typeof TelegramRoute
  '/parche/$code': typeof ParcheCodeRoute
  '/parche/crear': typeof ParcheCrearRoute
  '/parche_/$code/match': typeof ParcheCodeMatchRoute
  '/parche_/$code/quiz': typeof ParcheCodeQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenida'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/telegram'
    | '/parche/$code'
    | '/parche/crear'
    | '/parche/$code/match'
    | '/parche/$code/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenida'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/telegram'
    | '/parche/$code'
    | '/parche/crear'
    | '/parche/$code/match'
    | '/parche/$code/quiz'
  id:
    | '__root__'
    | '/'
    | '/bienvenida'
    | '/landing'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/telegram'
    | '/parche/$code'
    | '/parche/crear'
    | '/parche_/$code/match'
    | '/parche_/$code/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienvenidaRoute: typeof BienvenidaRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegistroRoute: typeof RegistroRoute
  TelegramRoute: typeof TelegramRoute
  ParcheCodeRoute: typeof ParcheCodeRoute
  ParcheCrearRoute: typeof ParcheCrearRoute
  ParcheCodeMatchRoute: typeof ParcheCodeMatchRoute
  ParcheCodeQuizRoute: typeof ParcheCodeQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche/crear': {
      id: '/parche/crear'
      path: '/parche/crear'
      fullPath: '/parche/crear'
      preLoaderRoute: typeof ParcheCrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche/$code': {
      id: '/parche/$code'
      path: '/parche/$code'
      fullPath: '/parche/$code'
      preLoaderRoute: typeof ParcheCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche_/$code/quiz': {
      id: '/parche_/$code/quiz'
      path: '/parche/$code/quiz'
      fullPath: '/parche/$code/quiz'
      preLoaderRoute: typeof ParcheCodeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche_/$code/match': {
      id: '/parche_/$code/match'
      path: '/parche/$code/match'
      fullPath: '/parche/$code/match'
      preLoaderRoute: typeof ParcheCodeMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienvenidaRoute: BienvenidaRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegistroRoute: RegistroRoute,
  TelegramRoute: TelegramRoute,
  ParcheCodeRoute: ParcheCodeRoute,
  ParcheCrearRoute: ParcheCrearRoute,
  ParcheCodeMatchRoute: ParcheCodeMatchRoute,
  ParcheCodeQuizRoute: ParcheCodeQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
